package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"time"
)

type AutoGenerated struct {
	PublishingOffice string    `json:"publishingOffice"`
	ReportDatetime   time.Time `json:"reportDatetime"`
	TargetArea       string    `json:"targetArea"`
	HeadlineText     string    `json:"headlineText"`
	Text             string    `json:"text"`
}

func main() {

	url := "https://www.jma.go.jp/bosai/forecast/data/overview_forecast/140000.json?"

	resp, _ := http.Get(url)
	defer resp.Body.Close()

	byteArray, _ := ioutil.ReadAll(resp.Body)

	jsonByte := ([]byte)(byteArray)
	data := new(AutoGenerated)

	if err := json.Unmarshal(jsonByte, data); err != nil {
		fmt.Println("JSON Unmarshal error", err)
		return
	}

	fmt.Println(data.Text)
}
